server:
  port: 19999
spring:
  application:
    name: springcloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mrfxz/bootTest #目录结尾不能是bootTest/，否则匹配不到
          search-paths: allConfigTemp








