#log4j2配置文件path
logging:
  config: classpath:log4j2_dev.xml

#mysql配置
mysql:
  host: 127.0.0.1:3306
  username: root
  password: root

# rabbitMQ配置
spring:
  application:
    name: spring-boot-rabbitmq
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: superZhu
    password: a123456

# redis配置
redis:
  host: 127.0.0.1



