server:
  port: 8888
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    register-with-eureka: false #是否向服务中心注册自己，默认true
    fetch-registry: false #是否检索服务中心服务 默认true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false #是否开启自我保护 ，默认true,自我保护打开时，已关停服务会一直显示在Eureka首页
spring:
  application:
    name:eureka-server
  security:
    user:
      name: root
      password: root
