server:
  port: 8001


# eureka 注册
eureka:
  client:
    healthcheck:
      enabled: true #开启健康检查（依赖spring-boot-starter-actuator）
    service-url:
      defaultZone: http://127.0.0.1:8888/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5 #心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 15 #发呆时间，即服务续约到期时间（缺省为90s）
spring:
  application:
    name: clent8001
feign:
  hystrix:
    enabled: true


