#log4j2配置文件path
logging:
  config: classpath:log4j2_dev.xml

#mysql配置
mysql:
  host: 192.168.1.67:3306
  username: centOs
  password: Switch1#

# rabbitMQ配置
spring:
  application:
    name: spring-boot-rabbitmq
  rabbitmq:
    host: 192.168.1.67
    port: 5672
    username: superZhu
    password: a123456

# redis配置
redis:
  host: 192.168.1.67

